services:
  db:
    image: postgres:15
    container_name: hn_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-hn_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hn_pass}
      POSTGRES_DB: ${POSTGRES_DB:-hn_db}
    ports:
      - "5432:5432"
    volumes:
      - hn_db_data:/var/lib/postgresql/data
      - ./hn_flask/init_articles.sql:/docker-entrypoint-initdb.d/init.sql:ro


  web:
    build: .
    container_name: hn_flask_app
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./hn_flask:/app/hn_flask
    environment:
      PYTHONPATH: /app
      FLASK_APP: hn_flask/app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER:-hn_user}:${POSTGRES_PASSWORD:-hn_pass}@db:5432/${POSTGRES_DB:-hn_db}

volumes:
  hn_db_data:
