services:
  db:
    image: postgres:15
    container_name: hn_postgres
    environment:
      POSTGRES_USER: hn_user
      POSTGRES_PASSWORD: hn_pass
      POSTGRES_DB: hn_db
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: hn_flask_app
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./hn_flask:/app/hn_flask
    environment:
      FLASK_APP: hn_flask/app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
