services:
  db:
    image: postgres:15
    container_name: hn_postgres
    environment:
      POSTGRES_USER: hn_user
      POSTGRES_PASSWORD: hn_pass
      POSTGRES_DB: hn_db
    ports:
      - "5432:5432"
    volumes:
      - hn_db_data:/var/lib/postgresql/data

volumes:
  hn_db_data:
